### ISSUE TITLE
App crashes after importing Olmo2 Instruct GGUF

### ISSUE THREAD

**Issue by adamo1139** [Vali-98/ChatterUI#123]
Model loaded: q8_0 from https://huggingface.co/Fishfishfishfishfish/OLMo-2-1124-7B-Instruct/tree/main

I imported this model to check if it's compatible, but it crashes the app. At the time of loading the gguf I had 0.8.3 beta 1. Moving back to 0.8.2 stable didn't help. Restarting a phone didn't help, cleaning cache also didn't help. I had to reset the app data (all of the chats, presets and 120GB of various models copied into the data were removed in the process) to fix it.

Importing incompatible GGUF shouldn't break the app.
Can I provide some kind of logs to help you fix this issue or can you try to replicate it in your setup (on an instance of an app where you don't want to lose data)?

**Comment by Vali-98** [comment]
First of all so sorry about your data loss. I have a clue as to why this happens, its due to `verifyModelList` which runs when the app starts. It should attempt to load up the model's metadata for entry into the internal model_data table, and *should* fail gracefully if it cannot initialize the GGUF file.. 

This was a necessary step to update from 0.7.10 to 0.8.0 due to migrating to the new DB system, but seems to have inadvertently caused a hardlock. It seems that for whatever reason this model causes the internal native engine to crash instead of throwing an error. Because this entry will always be missing when the app boots up, the app will continue to attempt to create data for it and crash.

I believe solution would be to prefill the db entry prior to loading the model, so that `verifyModelList` doesn't keep attempting to load said model. This will allow the app to launch while also creating the entry required for the user to delete said model. I will also consider checking llama.rn on ways to mitigate this issue.

**Comment by adamo1139** [comment]
No problem, I am often wiping all of the chat data anyway so there wasn't anything in there that I would be revisiting. I'll set up instruct prompting again (BTW deepseek prompt format being included in the app by default would be nice), import all of the models again and I'll be good.

I realized I gave you a bit of an accurate description of the issue. I was on 0.8.3 beta 1, I tried to import gguf there but import button wasn't working, so I moved back to 0.8.2, and imported the Olmo2 GGUF there, not on the 0.8.3 beta 1.  I did a clean install of 0.8.3 beta 2 now and it has the same issue - model import button is inactive. I'm not sure if it's a known bug hence I'm reporting it here.

**Comment by Vali-98** [comment]
> model import button is inactive. I'm not sure if it's a known bug hence I'm reporting it here.

Are you on a Samsung device? If so this is a known issue due to a SDK update, and will probably be fixed in beta3 - this bug affects all buttons in headers, even the hamburger in the main screen.

**Comment by Vali-98** [comment]
The main issue should be fixed in d17bf6a04a0aa5287bfd7e820d2b342898483023
