### ISSUE TITLE
New. Info to help choosing model to new user and Hugging Face feature

### ISSUE THREAD

**Issue by bi4key** [Vali-98/ChatterUI#138]
Menu -> Models 

1/
Add some info on top about which small model he can load, list of model example:
Llama 3.2 1B Q4
Gemma 2 2B Q4
Etc

2/
Add feature to search Hugging Face for models and download model direct to the App (like PocketPal)

**Comment by bi4key** [comment]
Some list of small LLM ( SLM ) :
https://parakeet-nest.github.io/awesome-slms/

**Comment by bi4key** [comment]
Other models to considered:

---- CHAT ----

Gemma 2 2B It Q4

.

Llama 3.2 3B It Q4

Llama 3.2 1B It Q8 / https://huggingface.co/unsloth/Llama-3.2-1B-Instruct-GGUF/blob/main/Llama-3.2-1B-Instruct-Q8_0.gguf

Llama 3.2 1B It Q4 / https://huggingface.co/unsloth/Llama-3.2-1B-Instruct-GGUF/blob/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf

.

SummLlama 3.2 3B It Q4

.

Qwen 2.5 3B It Q4

Qwen 2.5 1.5B It Q4

.

Phi 3.5 mini Q4

.

SmolLM2 360M It Q8

SmolLM2 1.7B It Q4 l https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/blob/main/SmolLM2-1.7B-Instruct-Q4_K_L.gguf 

.

Danube 3 Q4

Danube 2 Q4

---- CODE ----

Qwen 2.5 Code 3B It Q5

Qwen 2.5 Code 0.5B It Q8

---- NSFW ----

Impish LLAMA 3B Q4 l https://huggingface.co/mradermacher/Impish_LLAMA_3B-GGUF/blob/main/Impish_LLAMA_3B.Q4_K_M.gguf 

Gemmasutra Mini 2B v2 Q4

**Comment by Vali-98** [comment]
Due to how often models are released, any list of recommended models will need to be rotated out frequently and will be somewhat cumbersome to maintain. I already considered a recommendation list a few times, but it never seemed worth adding.

**Comment by lemyandr** [comment]
>Due to how often models are released, any list of recommended models will need to be rotated out frequently.

Are there are any Android- / phone-arch-specific "red flags" one should keep in mind all the same?

Eg. searching the issues here for "quantization" seems to imply that it has some performance relevance.

Are there some parameters mischoosing which could critically affect performance (like by a factor of 1.5, 2, or 10)? Or are new users more or less free to choose any model at all because possible performance affects will be in the range of, for instance, 5% or so?
