### ISSUE TITLE
template tutorial

### ISSUE THREAD

**Issue by stradeleve** [Vali-98/ChatterUI#141]
I'll be honest with you. At first, I was really having a hard time using the app. I first discovered Layla and PocketPal before this, but I found out that out of the three, PocketPal is more optimized, followed by this one, and the slowest is Layla. This is because ChatterUI is not really importing the model into the app. When you move or delete the model in the file manager, the model imported into ChatterUI will also be removed. 

I hope you don't mind this feedback of mine. I actually like ChatterUI because it has more features than those two apps. But, as I mentioned, I was having a hard time at first because there was no tutorial on what to do. So, I just used my common sense and import a model. I imported Llama 3.2 3B and chatted with it, but it was a very rough experience. I immediately sent it to the nearest mental hospital because it kept saying illogical stuff.

Today, I learned to visit the Instruct tab, and the default is Alpaca, so I just chose Llama 3, and finally, it is now working. However, I still have no idea how to create a template that will work with a specific model, even after trying trial and error. For example, I imported ChatGPT-2.V2.Q4_K_S.gguf, but there was no working template for it, so I also sent it to a mental hospital. I imported that model into Layla, and it worked, but it was still not that good, so I just gave up.

I browsed through the ChatterUI GitHub to see if I missed some useful information, which is why I ended up here writing a long issue. Sorry for the inconvenience. I'm just trying to be honest. Thanks.

**Comment by Vali-98** [comment]
Based on the HF page here: https://huggingface.co/suriya7/ChatGPT-2.V2, the model uses the `ChatML` format for text.

PocketPal and Layla might get away with running models since they use the model formatter preset within the GGUF file. The issue is that not all GGUF files have these fields properly set, so ChatterUI opts for user-controlled formatting, but because of this, the user has to be proactive in setting the right format.

I do not believe theres a good user-convinient solution since the GGUF chat template formatting is not strictly enforced, and anyone can upload GGUFs with missing template fields.
