### ISSUE TITLE
[Feature Request] Chat Completion [specifically OpenRouter] support and more...

### ISSUE THREAD

**Issue by Knifemint** [Vali-98/ChatterUI#2]
It's been a while since ChatterUI was updated. I wonder if there will be Chat Completion support like SillyTavern does.

I do also have other requests such as:
- Min P
- Summarize
- Other card details such as Personality summary, Scenario and Example of dialogue support

I do really like this app and have recommended to some of my friends. I hope y'all keep developing it. Thanks!

**Comment by Vali-98** [comment]
Hey there, I'm only working on this project in my free time. If I have some time to spare, I'll see to working on these features. Thanks for using my app.

**Comment by Vali-98** [comment]
Update:

Added:
- Open Router has been aded in early stages, though not yet as a release.
- Min P has been added to compatible backends.

In Development:
- Additional character customization is being worked on.

Unsupported:
- Summarize support likely won't be added due to requiring specific models that cannot be run natively.

This issue will be closed as most requested features have been added.

**Comment by Knifemint** [comment]
Thank you for the updates. As for the Summarize feature, I use the same model used for chatting on SillyTavern but I supposed there are more important features to be implemented first. Looking forward for the next updates. Cheers!
