### ISSUE TITLE
Disable auto scrolling when text is generating

### ISSUE THREAD

**Issue by Irobrine** [Vali-98/ChatterUI#24]
I would like auto scrolling to be disabled when text is generating. This would preferably be done with a toggle. At the moment, auto scrolling reduces text readability when generation is too fast.

**Comment by Vali-98** [comment]
Surprisingly this is a difficult feature to figure out due to how the chat listing works in react native. The current implementation isn't autoscrolling, it simply expands due to the expanding field being the first element in a reversed and inverted flatlist. 

I already attempted to prototype a few possible solutions to no success. Unfortunately this will likely not be added soon.

**Comment by Vali-98** [comment]
It turns out this was trivial after revising documentation: 
https://reactnative.dev/docs/scrollview#maintainvisiblecontentposition

It has since been added in f5f97dc0e5a92e6154991be967f811ee9501d717
