### ISSUE TITLE
Getting error message "Failed to generate locally: Error: Context not found"

### ISSUE THREAD

**Issue by Sphyker789** [Vali-98/ChatterUI#42]
I keep getting this error message most of the time and I've tested it on 4
![Screenshot_20240617_210636_ChatterUI](https://github.com/Vali-98/ChatterUI/assets/172508001/c8d9ccd1-8789-4a3f-be5b-658285b99c94)
 devices "Failed to generate locally: Error: Context not found"

**Comment by Vali-98** [comment]
Hey there, can you provide more information:
1. When this happens? At 0 context? 
2. Does this occur on the first message after startup?
3. What model is being used?
4. Are you using the context cache feature?

**Comment by Sphyker789** [comment]
I've disabled the context and it fixed it! Thanks a lot

**Comment by AdityaMH** [comment]
I can't find context cache too.
This bug also happen to me.

**Comment by AdityaMH** [comment]
I remove some system prompt like `Do not speak for user`.
It's work again to generate, but stopped in halfway. Like context getting limited somehow.

Increasing max context also didn't help.

After fork chat in middle conversation and continue from that chat, it's generated normal again.

Maybe too much input context (character+system prompt+entire chat) in one session can be culprit from beginning.
cutting input context by ignoring older chat maybe can help.
But we can't do that because no option to do it.
