### ISSUE TITLE
If generated tokens is higher than 256 output is a nonsense  to question 

### ISSUE THREAD

**Issue by mirek190** [Vali-98/ChatterUI#60]
Gemma 2b q8 - generated tokens  256 - answer is coherent 

![Screenshot_2024-08-07-12-49-24-464_com Vali98 ChatterUI](https://github.com/user-attachments/assets/e2bbb985-8fdc-478c-85d4-e18917347070)

![Screenshot_2024-08-07-12-49-06-500_com Vali98 ChatterUI](https://github.com/user-attachments/assets/3e024787-7833-4934-9e37-8c538ba97e26)

Gemma 2b q8 - generated tokens 4000 - answer has no sense to question 

![Screenshot_2024-08-07-12-49-43-270_com Vali98 ChatterUI](https://github.com/user-attachments/assets/6229356d-de21-49fd-bbf1-9ceb6ce95697)
![Screenshot_2024-08-07-12-50-27-030_com Vali98 ChatterUI](https://github.com/user-attachments/assets/c5720004-e785-443b-b081-8499c8eb7642)

**Comment by Vali-98** [comment]
This is actually intended behavior, similar issue to: https://github.com/Vali-98/ChatterUI/issues/55#issuecomment-2269612084

This is because Generated Tokens controls how many tokens are reserved for the generate context. if you set this too high, then the entire context is used for generated output and none for the context history. You can confirm this by enabling `Print Context`  in the settings menu to confirm that only the system prompt is added to the context for generations.

**Comment by mirek190** [comment]
Maybe you could link max tokens ( ctx) for model to Generated Tokens option ?
