### ISSUE TITLE
Support for ARM optimized gguf?

### ISSUE THREAD

**Issue by mlsterpr0** [Vali-98/ChatterUI#86]
There are gguf's that run much faster on android arm processors. Like for example here: 
https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF
If you scroll down you can see:
Llama-3.2-3B-Instruct-Q4_0_4_4.gguf | Q4_0_4_4 | 1.92GB Optimized for ARM inference. Should work well on all ARM chips, pick this if you're unsure.
I tried those gguf's in another app, and indeed they are much faster. But this app crashes when you try to load it.

**Comment by Vali-98** [comment]
This probably is due cui-llama.rn being outdated on the current 0.7.10 release. Likely due to the asserts which have since been removed:

https://github.com/ggerganov/llama.cpp/commit/1e436302188a704ac9ea044af03193648806f19c

I will have to updated cui-llama.rn, though probably as a pre-release as 0.8.0 isn't ready yet.

**Comment by Vali-98** [comment]
Release made:

https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.0-beta3

Tested - loading Q4_0_4_4 on a Q4_0_4_8 capable device now works!
