### ISSUE TITLE
QLoRA support?

### ISSUE THREAD

**Issue by jadbox** [Vali-98/ChatterUI#95]
Meta just rolled out special Llama 3.2 3b models with better compression with QLoRA. I'm not sure if it's supported?

**Comment by Vali-98** [comment]
QLoRA isn't a quantization method, but a way to finetune a model to account for quantization.

The Meta post on HF describes training with QAT followed by finetuning via LoRA, the model itself seems to be in some raw pytorch format for now. We will need to wait for someone to convert the model to HF format, then GGUF. Otherwise I'm not sure why it wouldn't work.

Either way, this is more of a llama.cpp issue than it is a ChatterUI one.
